url: "https://avalunch.github.io"
baseurl: ""
title: AvaLunch
description: Candid Lunch Recommendations for the UH @ Manoa Campus
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
