url: "https://avalunch.github.io"
baseurl: ""
title: AvaLunch
description: Description Page for AvaLunch final project
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
